[package]
name = "tinyhttp-fortanix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# enable TLS support via rustls
tiny_http = { version = "0.12.0", features = ["ssl-rustls"] }
[patch.crates-io]
# tiny http uses ring which needs to be patched to work properly 
# and securely in SGX target
ring = { git = 'ssh://git@github.com/mithril-security/ring.git', branch="fortanix-target"}

[package.metadata.fortanix-sgx]
threads=10
