name: end-to-end tests

on: push

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      
      - name: Build test image
        run: docker build -f .devcontainer/Dockerfile --tag blindaiv2-test:latest --target test .
      
      - name: Run end-to-end tests
        run: docker run --device /dev/sgx/enclave --device /dev/sgx/provision blindaiv2-test
