name: end-to-end tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      
      - name: Build test image
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          tags: blindaiv2-test:latest
          context: .
          file: .devcontainer/Dockerfile
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run end-to-end tests
        run: docker run blindaiv2-test

