name: end-to-end tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      
      - name: Run tests in container
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          context: .
          file: .devcontainer/Dockerfile
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

